{% set name = "pyprocar" %}
{% set version = "6.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyProcar-{{ version }}.tar.gz
  sha256: 76eaa5ecdcb6228fedbbe288b18e85cced45fb1b2d7239e8974caf707f326488

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ase
    - importlib-metadata
    - matplotlib-base
    - mscorefonts
    - python >=3.6
    - pychemia
    - pyvista
    - pyvistaqt
    - scikit-image
    - scipy
    - seekpath
    - trimesh

test:
  imports:
    - pyprocar
    - pyprocar.abinitparser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/romerogroup/pyprocar
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: A Python library for electronic structure pre/post-processing.

  description: |
    PyProcar is a robust, open-source Python library used for pre- and
    post-processing of the electronic structure data coming from DFT
    calculations. PyProcar provides a set of functions that manage data
    obtained from the PROCAR format. Basically, the PROCAR format is a
    projection of the Kohn-Sham states over atomic orbitals. That
    projection is performed to every k-point in the considered mesh,
    every energy band and every atom. PyProcar is capable of performing
    a multitude of tasks including plotting plain and spin/atom/orbital
    projected band structures and Fermi surfaces- both in 2D and 3D, Fermi
    velocity plots, unfolding bands of a super cell, comparing band
    structures from multiple DFT calculations, plotting partial density
    of states and generating a k-path for a given crystal structure.
  doc_url: https://romerogroup.github.io/pyprocar/
  dev_url: https://github.com/romerogroup/pyprocar

extra:
  recipe-maintainers:
    - jan-janssen
    - uthpalaherath
    - logan-lang
